// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoonlightDashboard.Database;

#nullable disable

namespace MoonlightDashboard.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260614154205_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("MoonlightDashboard.Database.Models.Arma3CreatorDlc", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Depot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manifest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Arma3CreatorDlcs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "arma3creatordlc_019ec6cc-1760-7205-adf6-c908ec83b2a3",
                            Created = new DateTime(2026, 6, 14, 15, 42, 4, 629, DateTimeKind.Utc).AddTicks(3063),
                            Depot = "233790",
                            Manifest = "7907683864326938845",
                            Name = "S.O.G. Prairie Fire",
                            ShortName = "vn",
                            Updated = new DateTime(2026, 6, 14, 15, 42, 4, 629, DateTimeKind.Utc).AddTicks(3063)
                        },
                        new
                        {
                            Id = "arma3creatordlc_019ec6cc-1762-70d4-bea1-244015ed52db",
                            Created = new DateTime(2026, 6, 14, 15, 42, 4, 642, DateTimeKind.Utc).AddTicks(7554),
                            Depot = "233787",
                            Manifest = "5132611187809370715",
                            Name = "Global Mobilization - Cold War Germany",
                            ShortName = "gm",
                            Updated = new DateTime(2026, 6, 14, 15, 42, 4, 642, DateTimeKind.Utc).AddTicks(7554)
                        },
                        new
                        {
                            Id = "arma3creatordlc_019ec6cc-1762-70d5-98a8-6bf3be2d0456",
                            Created = new DateTime(2026, 6, 14, 15, 42, 4, 642, DateTimeKind.Utc).AddTicks(7680),
                            Depot = "233786",
                            Manifest = "4838971061001777332",
                            Name = "Western Sahara",
                            ShortName = "ws",
                            Updated = new DateTime(2026, 6, 14, 15, 42, 4, 642, DateTimeKind.Utc).AddTicks(7680)
                        },
                        new
                        {
                            Id = "arma3creatordlc_019ec6cc-1762-70d6-8732-c6969ccb2c99",
                            Created = new DateTime(2026, 6, 14, 15, 42, 4, 642, DateTimeKind.Utc).AddTicks(7693),
                            Depot = "1294440",
                            Manifest = "3088033651234564230",
                            Name = "CSLA Iron Curtain",
                            ShortName = "csla",
                            Updated = new DateTime(2026, 6, 14, 15, 42, 4, 642, DateTimeKind.Utc).AddTicks(7693)
                        });
                });

            modelBuilder.Entity("MoonlightDashboard.Database.Models.Arma3Modset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Arma3Modsets", (string)null);
                });

            modelBuilder.Entity("MoonlightDashboard.Database.Models.Arma3ModsetMod", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModSteamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModsetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Arma3ModsetMods", (string)null);
                });

            modelBuilder.Entity("MoonlightDashboard.Database.Models.Arma3Server", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveModsetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalCommandlineArgs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Arma3Servers", (string)null);
                });

            modelBuilder.Entity("MoonlightDashboard.Database.Models.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("MoonlightDashboard.Database.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActivationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
