// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoonlightDashboard.Database;

#nullable disable

namespace MoonlightDashboard.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("MoonlightDashboard.Database.Models.Arma3CreatorDlc", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Depot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manifest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Arma3CreatorDlcs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "arma3creatordlc_prairie_fire",
                            Created = new DateTime(2026, 6, 28, 12, 0, 0, 0, DateTimeKind.Utc),
                            Depot = "1227701",
                            Manifest = "8778927882579535691",
                            Name = "S.O.G. Prairie Fire",
                            ShortName = "vn",
                            Updated = new DateTime(2026, 6, 28, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "arma3creatordlc_global_mobilization",
                            Created = new DateTime(2026, 6, 28, 12, 0, 0, 0, DateTimeKind.Utc),
                            Depot = "1042221",
                            Manifest = "2053062434401462647",
                            Name = "Global Mobilization - Cold War Germany",
                            ShortName = "gm",
                            Updated = new DateTime(2026, 6, 28, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "arma3creatordlc_western_sahara",
                            Created = new DateTime(2026, 6, 28, 12, 0, 0, 0, DateTimeKind.Utc),
                            Depot = "1681171",
                            Manifest = "738528337327303663",
                            Name = "Western Sahara",
                            ShortName = "ws",
                            Updated = new DateTime(2026, 6, 28, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "arma3creatordlc_iron_courtain",
                            Created = new DateTime(2026, 6, 28, 12, 0, 0, 0, DateTimeKind.Utc),
                            Depot = "1294441",
                            Manifest = "5407594059006667059",
                            Name = "CSLA Iron Curtain",
                            ShortName = "csla",
                            Updated = new DateTime(2026, 6, 28, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "arma3creatordlc_expeditionary_forces",
                            Created = new DateTime(2026, 6, 28, 12, 0, 0, 0, DateTimeKind.Utc),
                            Depot = "2647831",
                            Manifest = "2687171635229708487",
                            Name = "Expeditionary Forces",
                            ShortName = "ef",
                            Updated = new DateTime(2026, 6, 28, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "arma3creatordlc_reaction_forces",
                            Created = new DateTime(2026, 6, 28, 12, 0, 0, 0, DateTimeKind.Utc),
                            Depot = "2647761",
                            Manifest = "2576413575760136050",
                            Name = "Reaction Forces",
                            ShortName = "rf",
                            Updated = new DateTime(2026, 6, 28, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "arma3creatordlc_spearhead_1944",
                            Created = new DateTime(2026, 6, 28, 12, 0, 0, 0, DateTimeKind.Utc),
                            Depot = "1175381",
                            Manifest = "6576197082193427041",
                            Name = "Spearhead 1944",
                            ShortName = "spe",
                            Updated = new DateTime(2026, 6, 28, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MoonlightDashboard.Database.Models.Arma3Modset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Arma3Modsets", (string)null);
                });

            modelBuilder.Entity("MoonlightDashboard.Database.Models.Arma3ModsetMod", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModSteamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModsetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Arma3ModsetMods", (string)null);
                });

            modelBuilder.Entity("MoonlightDashboard.Database.Models.Arma3Server", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveModsetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalCommandlineArgs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Port")
                        .IsUnique();

                    b.ToTable("Arma3Servers", (string)null);
                });

            modelBuilder.Entity("MoonlightDashboard.Database.Models.Arma3ServerCreatorDlc", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arma3CreatorDlcId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Arma3ServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Arma3ServerCreatorDlcs", (string)null);
                });

            modelBuilder.Entity("MoonlightDashboard.Database.Models.Job", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CancellationRequested")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("MoonlightDashboard.Database.Models.ModInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModId")
                        .IsUnique();

                    b.ToTable("ModInfos", (string)null);
                });

            modelBuilder.Entity("MoonlightDashboard.Database.Models.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "permission_admin",
                            Created = new DateTime(2026, 6, 28, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Admin",
                            Updated = new DateTime(2026, 6, 28, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MoonlightDashboard.Database.Models.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("MoonlightDashboard.Database.Models.SettingValue", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SettingValues", (string)null);
                });

            modelBuilder.Entity("MoonlightDashboard.Database.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActivationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MoonlightDashboard.Database.Models.UserPermission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserPermissions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
